# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 00:38
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_api', '0002_auto_20160210_1503'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='access',
            name='refresh_token',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='access',
            name='token',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='code',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
